config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles, :videos
  get '/admin', to: 'users#index', as: 'admin'
  get '/video/:id/comment', to: 'videos#comment', as: 'comment_video'
  post '/video/:id/comment', to: 'videos#save_comment', as: 'save_comment_video'
  match '/videocomment/', to: 'videos#destroy_comment', via: [:delete]
  match '/videocomment/:id', to: 'videos#destroy_comment', as: 'deletevideocomment', via: [:delete],
                             defaults: { format: 'js' }

  get '/article/:id/comment', to: 'articles#show_comment', as: 'comment_article'
  post '/article/:id/comment', to: 'articles#save_comment', as: 'save_comment_article'
  match '/articlecomment/:id', to: 'articles#destroy_comment', as: 'deletearticlecomment', via: [:delete],
                               defaults: { format: 'js' }
  match '/admin/users/:id', to: 'users#toggle_admin', via: [:post], as: 'toggleadmin', defaults: { format: 'js' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comment_articles, dependent: :delete_all
  validates :body, :title, :presence => true
end

app/models/comment_article.rb
class CommentArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :body, :presence => true
end

app/models/comment_video.rb
class CommentVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video
  validates :body, :presence => true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comment_videos
  has_many :comment_articles
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :comment_videos, dependent: :delete_all
  validates :title, :url, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protected

  def authenticate_admin!
    authenticate_user!
    redirect_to articles_path, status: :forbidden unless current_user.admin?
  end

  def authenticate_banned!
    authenticate_user!
    redirect_to cancel_user_registration_path, status: :forbidden if current_user.banned?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: %i[destroy edit update destroy_comment]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    redirect_to articles_path unless current_user.admin

    @article = Article.new
  end

  def edit
    redirect_to articles_path unless current_user.admin
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Artigo criado com sucesso.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if current_user.admin
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Artigo atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to articles_path
    end
  end

  def destroy
    if current_user.admin
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Artigo removido com sucesso.' }
        format.json { head :no_content }
      end
    else
      redirect_to articles_path
    end
  end

  def save_comment
    @user = current_user
    @comment = @user.comment_articles.create(body: params["comment_text_#{params[:id]}".to_sym], article_id: params[:id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comentário criado com sucesso.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  def destroy_comment
    @comment = CommentArticle.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js {}
    end
  end

  def show_comment
    @comment = CommentArticle.find(params[:id])
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def set_banned
    @user = User.find(current_user.id)
    @user.banned = true
  end

  def toggle_admin
    @user = User.find(params[:id])
    @user.admin = !@user.admin
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_path }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: %i[destroy edit update destroy_comment]

  def index
    @videos = Video.all
  end

  def show; end

  def new
    @video = Video.new
  end

  def edit; end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Vídeo criado com sucesso.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Vídeo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Vídeo removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  def save_comment
    @user = current_user
    @comment = @user.comment_videos.create(body: params["comment_text_#{params[:id]}".to_sym], video_id: params[:id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @video, notice: 'Comentário criado com sucesso.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  def destroy_comment
    @comment = CommentVideo.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_admin?
    current_user.admin
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> proibiram esse artigo de ser salvo:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-6 offset-3">
  <div class="field">
    <%= form.label :título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class:'btn btn-success btn-sm' %>
  </div>
  </div>
<% end %>

app/views/articles/_form_comment.html.erb
<%= form_with url: comment_article_path(article), local: false, id: 'comment_form' do |form| %>
  <div class="field">
    <%= form.label :comentar %>
    <%= form.text_area "comment_text_#{article}" %>
  </div>

  <div class="actions">
    <%= form.submit "Comentar", class:'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/articles/destroy_comment.js.erb
document.querySelector('#comment_<%= @comment.id %>').remove()

app/views/articles/edit.html.erb
<h1>Editar Artigos</h1>

<%= render 'form', article: @article %>

<%= link_to 'Mostrar', @article, class:'btn btn-success btn-sm'%>  
<%= link_to 'Voltar', articles_path, class:'btn btn-warning btn-sm' %>

app/views/articles/index.html.erb
<h1>Artigos</h1>
<% if user_admin? %>
<%= link_to 'Novo Artigo', new_article_path, class:'btn btn-success'%>
<% end %>

<% @articles.each do |article| %>
  <div class='col-10 offset-1'>
    <h3><%= article.title %></h3>
    <p><%= article.body %></p>
    <% if user_admin? %>
      <%= link_to 'Mostrar', article, class:'btn btn-success btn-sm' %>
      <%= link_to 'Editar', edit_article_path(article), class:'btn btn-warning btn-sm' %>
      <%= link_to 'Remover', article, method: :delete, data: { confirm: 'Tem certeza?' },class:'btn btn-danger btn-sm' %>
    <% end %>
    
    <div id='comments_<%= article.id %>'>
      <h5>Comentários</h5>
    <%= render 'form_comment', :article => article.id %>

      <ul class="list-group" id="comments_list_<%= article.id %>">
      <% article.comment_articles.reverse.each do |comment| %>
        <li class="list-group-item" id="comment_<%= comment.id %>"><%= comment.user.email %>:<p>"<%= comment.body %>"</p>
        <% if user_admin? %>
          <%= link_to 'Remover Comentário', deletearticlecomment_url(comment.id), method: :delete, local: false, remote: true, data: { confirm: 'Tem certeza?' } %>
        <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>Novo Artigo</h1>

<%= render 'form', article: @article %>

<%= link_to 'Voltar', articles_path, class:'btn btn-primary btn-sm' %>

app/views/articles/save_comment.js.erb
document.querySelector('#comments_list_<%= @comment.article.id %>').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @comment) %>') ;
document.querySelector('#comment_text_<%= @comment.article.id %>').value=""

app/views/articles/show.html.erb
<p>
  <strong>Título:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @article.body %>
</p>
<% if user_admin? %>
  <%= link_to 'Editar', edit_article_path(@article), class:'btn btn-warning btn-sm' %> 
<% end %>
<%= link_to 'Voltar', articles_path, class:'btn btn-primary btn-sm' %>

app/views/comment_articles/_comment_article.js.erb
<li class="list-group-item" id="comment_<%= @comment.id%>"><%=@comment.user.email%><p>"<%=@comment.body%>"</p>
    <% if user_admin? %>
        <%= link_to 'Remover Comentário', deletearticlecomment_url(@comment.id), method: :delete, local: false, remote: true, data: { confirm: 'Tem certeza?' } %>
    <% end %>
</li>                     

app/views/comment_videos/_comment_video.js.erb
<li class="list-group-item" id="comment_<%= @comment.id%>"><%=@comment.user.email%><p>"<%=@comment.body%>"</p>
    <% if user_admin? %>
        <%= link_to 'Remover Comentário', deletevideocomment_url(@comment.id), method: :delete, local: false, remote: true, data: { confirm: 'Tem certeza?' } %>
    <% end %>
</li>                     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>NewsRuby</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
       <%= stylesheet_link_tag 'application', media: 'all' %>
       <%# <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
       <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">RubyNews</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Artigos', articles_url, :class => 'nav-link' %>

          </li>
          <li class="nav-item active">
            <%= link_to 'Vídeos', videos_url, :class => 'nav-link' %>

          </li>
          <% if current_user %>
          
           <% if user_admin? %>
          <li class="nav-item active">
            <%= link_to 'Publicar Artigo', new_article_url, :class => 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Publicar Vídeo', new_video_url, :class => 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Admin Users', '/admin', :class => 'nav-link' %>
          </li>
          <% end %>
        <% end %>
        </ul>
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
      </div>
    </div>
  </nav>
  <% if notice %>
    <p class="alert alert-success">
      <%= notice %>
    </p>
    <% end %>
      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
        <% end %>
          <div class="container">
            <%= yield %>
          </div>
    
          
</body>

</html>

app/views/users/_user.js.erb
<%= user.email %> - 
    <% if user.admin %>
      ADMIN - <%= link_to 'Revogar Admin', toggleadmin_url(user.id), method: :post, data: { confirm: 'Tem certeza?' }, local: false, remote: true, class:'btn btn-danger btn-sm' %>
    <% else %>
      Comum - <%= link_to 'Atribuir Admin', toggleadmin_url(user.id), method: :post, data: { confirm: 'Tem certeza?' }, local: false, remote: true, class:'btn btn-warning btn-sm' %>
    <% end %>
    

app/views/users/index.html.erb
<h1>Usuários</h1>

<ul class="list-group" id="users_list">
  <% @users.each do |user| %>
    <li class="list-group-item" id="user_<%= user.id %>" ><%= user.email %> - 
    <% if user.admin %>
      ADMIN - <%= link_to 'Revogar Admin', toggleadmin_url(user.id), method: :post, data: { confirm: 'Tem certeza?' }, local: false, remote: true, class:'btn btn-danger btn-sm' %>
    </li>
    <% else %>
      Comum - <%= link_to 'Atribuir Admin', toggleadmin_url(user.id), method: :post, data: { confirm: 'Tem certeza?' }, local: false, remote: true, class:'btn btn-warning btn-sm' %>
    </li>
    <% end %>
<% end %>
</ul>

app/views/users/toggle_admin.js.erb
var user = document.querySelector('#user_<%= @user.id %>')
var li = document.createElement('li')
user.innerHTML  = '<%= escape_javascript(render @user) %>'

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> proíbem esse video de ser salvo:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :URL %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class:'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/videos/_form_comment.html.erb
<%= form_with url: comment_video_path(video), local: false, id: 'comment_form' do |form| %>
  <div class="field">
    <%= form.label :comentar %>
    <%= form.text_area "comment_text_#{video}" %>
  </div>

  <div class="actions">
    <%= form.submit "Comentar", class:'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/videos/destroy_comment.js.erb
document.querySelector('#comment_<%= @comment.id %>').remove()

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video,class:'btn btn-warning btn-sm' %> |
<%= link_to 'Back', videos_path, class:'btn btn-primary btn-sm' %>

app/views/videos/index.html.erb
<h1>Videos</h1>
<% if user_admin? %>
<%= link_to 'Novo Vídeo', new_video_path, class:'btn btn-success' %>
<% end %>

<% @videos.each do |video| %>
  <div class='col-6 offset-3'>
    <h3><%= video.title %></h3>
    <iframe width="560" height="315" src='<%= video.url %>' frameborder="0" allow="encrypted-media" allowfullscreen></iframe>
    <% if user_admin? %>
      <%= link_to 'Mostrar', video, class:'btn btn-success' %>
      <%= link_to 'Editar', edit_video_path(video), class:'btn btn-warning' %>
      <%= link_to 'Remover', video, method: :delete, data: { confirm: 'Tem certeza?' },class:'btn btn-danger' %>
    <% end %>
    <div id='comments'>
      <h5>Comentários</h5>
    <%= render 'form_comment', :video => video.id %>

      <ul class="list-group" id="comments_list_<%= video.id %>">
        <% video.comment_videos.reverse.each do |comment| %>
          <li class="list-group-item" id="comment_<%= comment.id %>"><%= comment.user.email %>:<p>"<%= comment.body %>"</p>
          <% if user_admin? %>
            <%= link_to 'Remover Comentário', deletevideocomment_url(comment.id), method: :delete, local: false, remote: true, data: { confirm: 'Tem certeza?' } %>
          <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/new.html.erb
<h1>Novo Vídeo</h1>

<%= render 'form', video: @video %>

<%= link_to 'Voltar', videos_path, class:'btn btn-primary btn-sm' %>

app/views/videos/save_comment.js.erb
document.querySelector('#comments_list_<%= @comment.video.id %>').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @comment) %>') ;
document.querySelector('#comment_text_<%= @comment.video.id %>').value="" 

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @video.title %>
</p>

<p>
  <iframe width="560" height="315" src='<%= @video.url %>' frameborder="0" allow="encrypted-media" allowfullscreen></iframe>
</p>

<%= link_to 'Editar', edit_video_path(@video), class:'btn btn-warning btn-sm'%> 
<%= link_to 'Voltar', videos_path, class:'btn btn-primary btn-sm'%>